name: 'Terraform-Plan'

# on:
#   push:
#     branches: 
#       - main
on:
  workflow_dispatch:
    inputs:
      tfvars_file:
        description: 'Path to the .tfvars file'
        required: true
        default: 'dev.tfvars'
      action:
        type: choice
        description: 'Terraform Action'
        options:
          - plan
          - apply
        required: true
        default: 'apply'

env: 
  AWS_REGION: ap-south-1

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Infra Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.10.0
          terraform_wrapper: true

      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::104824081961:role/GitHubActionsOIDCRole-104824081961
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt --recursive

      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      # - name: Terraform plan
      #   run: |
      #     terraform plan -var-file=dev.tfvars -out=tfplan
    
      # - name: Terraform Apply
      #   run: |
      #     terraform apply -auto-approve tfplan

    #   - name: Terraform Destroy
    #     run: |
    #       terraform plan -destroy -out=dev-tfplan -input=false
    #       terraform apply dev-tfplan

        

            